version: "3.5"
services:
  front-application:
    container_name: git-list-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
    ports:
      - "4000:8080"
